### ISSUE TITLE
Add Meedan URL

### ISSUE THREAD

**Issue by infojunkie** [meedan/montage#3]
In addition to https://montage.storyful.com, the app should be accessible via https://montage.meedan.com.

**Comment by caiosba** [comment]
We are now able to deploy to live. This is available on the `docker-compose` branch. The required changes on code are at https://github.com/meedan/montage/compare/3bb6742e7775fee58b00aa98c53fb1c53135062c...85b1f7015ddf4e93d89edc2ffa0c3178100cf61e. Explanations about the changes:

1) On `appengine/app.yaml`, I had to put the version of the SSL module as 2.7.11. This is because of this: https://cloud.google.com/appengine/docs/deprecations/python-ssl-27. In summary, we were using a version of the Python SSL module which is not allowed by Google Cloud anymore, so we had to upgrade.

2) On `requirements.txt`, I had to upgrade `httplib2` to 0.11.3 (https://pypi.org/project/httplib2/#history), because 0.9.2 was giving a SSL error

3) On `appengine/src/greenday_public/templates/index.html` I added a metatag for domain verification (montage.meedan.com)

4) On `buildout.cfg` I upgraded the AppEngine SDK from 1.9.35 to latest version 1.9.73, also because of the Python SSL upgrade (the SDK version 1.9.35 was not compatible with Python SSL 2.7.11)

5) I added a NPM script to `package.json` because simplying running `grunt` was getting the `grunt` binary from Python, not the one from `node_modules`:

```
  "scripts": {
     "grunt-deploy-prod": "grunt deployProd"
   },
```

6) I updated the documentation on `README` to reflect the live deployment recipe that actually works and clarifying that right now we can do that from inside the Docker container because the deployment task opens a browser tab for Google authentication

7) On the Google Cloud side, I had to add the Meedan domains to https://console.developers.google.com/apis/credentials/oauthclient/583467124136-qkjiv5reqndcj60hf9qg79ikv8vdi51u.apps.googleusercontent.com?project=greenday-project&folder&organizationId=923341443555

I deployed to live and it worked. Now we are at version 3.0.24. Montage now works from the Meedan domain as well: https://montage.meedan.com/my-projects.
