### ISSUE TITLE
Create local development environment

### ISSUE THREAD

**Issue by infojunkie** [meedan/montage#4]
Create a Docker Compose file that spins up the Montage app locally. Ensure that it's easy to modify the local source files and see the changes in the locally running app.

**Comment by caiosba** [comment]
Besides the steps listed on https://github.com/meedan/montage/tree/docker-compose#montage, the only other thing I had to do in order to run it locally (outside Docker) was to create a `appengine/src/greenday_core/settings/local.py` file based on `appengine/src/greenday_core/settings/local.py.sample`.

**Comment by Ahmid** [comment]
I also added 
```
libjpeg-dev
```
inside the Dockerfile step-2 for this to run.

**Comment by infojunkie** [comment]
The `docker-compose` branch should be functional now cc @Laurian
